//App actions
export const LOADING = 'LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const OPEN_MENU = 'OPEN_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';
export const TOGGLE_USER_MENU = 'TOGGLE_USER_MENU';

//House audit actions
export const GET_HOUSE_LIST = 'GET_HOUSE_LIST';
export const GET_HOUSE_AUDIT = 'GET_HOUSE_AUDIT';
export const SAVE_HOUSE_AUDIT = 'SAVE_HOUSE_AUDIT';
export const DELETE_HOUSE_AUDIT = 'DELETE_HOUSE_AUDIT';
export const UPDATE_HOUSE_AUDIT = 'UPDATE_HOUSE_AUDIT';

// House Audit Details
export const GET_HOUSE_AUDIT_TEMPLATE = 'GET_HOUSE_AUDIT_TEMPLATE';
export const HOUSE_AUDIT_ITEM_CHANGE = 'HOUSE_AUDIT_ITEM_CHANGE';
export const HOUSE_AUDIT_FIELD_CHANGE = 'HOUSE_AUDIT_FIELD_CHANGE';
export const HOUSE_AUDIT_FINDING_CHANGE = 'HOUSE_AUDIT_FINDING_CHANGE';

//Other actions
export const ANOTHER_ACTION = 'ANOTHER_ACTION';